name: Build and Deploy Angular App

on:
  push:
    branches:
      - main  # Déclenchement lors d'un push sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le dépôt
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configurez Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Version de Node.js à utiliser

      # Étape 3 : Installez les dépendances
      - name: Install Dependencies
        run: npm ci  # Utilisez npm ci pour des installations propres et rapides

      # Étape 5 : Déplacez les fichiers du sous-dossier 'browser'/Move Files to Root (clean then move)
      - name: Move Files to Root
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          if [ -d "./dist/amiapp/browser" ]; then
            rsync -a ./dist/amiapp/browser/ ./dist/amiapp/
            rm -rf ./dist/amiapp/browser
          else
            echo "Directory ./dist/amiapp/browser does not exist"
            exit 1
          fi

      # Étape 6 : Déployez sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GH_SECRETAMIAPP}}  # Token d'accès pour l'authentification
          publish_dir: ./dist/amiapp/  # Répertoire à publier sur GitHub Pages
