name: Build and Deploy Angular App

on:
  push:
    branches:
      - main  # Déclenchement lors d'un push sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Étape 3 : Installation des dépendances
      - name: Install Dependencies
        run: npm ci

      # ✅ Étape 4 : Build Angular
      - name: Build Angular App
        run: npm run build -- --configuration=production

      # Étape 5 : Déplacement du contenu de `dist/amiapp/browser` vers `dist/amiapp`
      - name: Move Files to Root
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          if [ -d "./dist/amiapp/browser" ]; then
            rsync -a ./dist/amiapp/browser/ ./dist/amiapp/
            rm -rf ./dist/amiapp/browser
          else
            echo "Directory ./dist/amiapp/browser does not exist"
            exit 1
          fi

      # ✅ Étape 6 : Création du fichier CNAME (automatique)
      - name: Create CNAME file
        run: echo "ami-platform.com" > ./dist/amiapp/CNAME

      # Étape 7 : Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_SECRETV2AMIAPP }}
          publish_dir: ./dist/amiapp/
