name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # or 'main', depending on your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Updated to Node.js version 20

    - name: Install dependencies
      run: npm install

    - name: Build the Angular app
      run: npm run build -- --configuration production --output-path=docs/browser --base-href="/amiapp/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.AMIAPP_TOKEN }}
        publish_dir: ./docs/browser # Deploy directly from docs/browser
