name: Build and Deploy Angular App

on:
  push:
    branches:
      - main  # Déclenchement lors d'un push sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le dépôt
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Configurez Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Version de Node.js à utiliser

      # Étape 3 : Installez les dépendances
      - name: Install Dependencies
        run: npm ci  # Utilisez npm ci pour des installations propres et rapides

      # Étape 4 : Construisez le projet Angular
      - name: Build Angular Project
        run: npm run build -- --output-path=dist/amiapp  # Construisez l'application

      # Étape 5 : Déplacez les fichiers du sous-dossier 'browser'
      - name: Move Files to Root
        run: |
          mkdir -p ./dist/amiapp/root && mv ./dist/amiapp/browser/* ./dist/amiapp/root/
          
      # Étape 6 : Déployez sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.AMIAPP_TOKEN}}  # Token d'accès pour l'authentification
          publish_dir: ./dist/amiapp/root  # Répertoire à publier sur GitHub Pages
